---
- name: Ensure ssl cert directory exists
  file: path="{{ smtp_cert_path }}/postfix-mta" state=directory
- name: Ensure ssl key directory exists
  file: path="{{ smtp_key_path }}/postfix-mta" state=directory
- name: Generate a self-signed cert.
  become: true
  command: >
     openssl req -newkey rsa:2048 -nodes -sha256 -x509 -subj "/CN=postfix-mta" -days 90 -keyout "{{ smtp_key_path }}"/postfix-mta/privkey.pem -out "{{ smtp_cert_path }}"/postfix-mta/cert.pem
  args:
    creates: "{{ smtp_key_path }}/postfix-mta/privkey.pem"

- name: Apply templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - src: main.cf.j2
      dest: /etc/postfix/main.cf
    - src: sasl_passwd.j2
      dest: /etc/postfix/sasl_passwd
- name: Generate SASL postmap
  command: postmap /etc/postfix/sasl_passwd
  args:
    chdir: /etc/postfix
