---
# tasks file for postfix-mta

- include: yum.yml
  sudo: yes

- include: stunnel.yml
  sudo: yes
  when: not smtp_start_tls

- include: configure.yml
  sudo: yes

- include: services.yml
  sudo: yes
