---
# tasks file for postfix-mta

- include: yum.yml
  become: true

- include: stunnel.yml
  become: true
  when: not smtp_start_tls

- include: sender.yml
  become: true
  when: use_sender_maps

- include: configure.yml
  become: true

- include: services.yml
  become: true

- include: assets.yml
  become: true
