---
- name: Install yum packages
  yum:
    name: stunnel
    state: latest
- name: stunnel chroot dir
  file:
    path: /var/lib/stunnel
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
- name: Add stunnel to systemd
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    mode: 0644
    owner: root
    group: root
  with_items:
    - stunnel.service
- name: Apply templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - src: stunnel.conf.j2
      dest: /etc/stunnel/stunnel.conf
