---
- name: Ensure ssl cert directory exists
  file: path="{{ smtp_cert_path }}/localhost" state=directory
- name: Ensure ssl key directory exists
  file: path="{{ smtp_key_path }}/localhost" state=directory
- name: Ensure Apache is stopped
  service:
    name: httpd
    state: stopped
- name: Generate a self-signed cert.
  sudo: yes
  command: >
     openssl req -newkey rsa:2048 -nodes -sha256 -x509 -subj "/CN=localhost" -days 90 -keyout "{{ smtp_key_path }}"/localhost/privkey.pem -out "{{ smtp_cert_path }}"/localhost/cert.pem
  args:
    creates: "{{ smtp_key_path }}/localhost/privkey.pem"
- name: stunnel chroot dir
  file:
    path: /var/lib/stunnel
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
- name: Add stunnel to systemd
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    mode: 0644
    owner: root
    group: root
  with_items:
    - stunnel.service
- name: Apply templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - src: stunnel.conf.j2
      dest: /etc/stunnel/stunnel.conf
